const fs=require('fs'),path=require('path');
const L=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
const esc=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const city=L.address.split(',').slice(-2).join(',').replace(/\s+\d{5}$/,'').trim();
const q=encodeURIComponent(L.name+', '+L.address);
const TH=L.theme;const V={mascot:esc(L.mascot),name:esc(L.name),short:esc(L.short),initial:esc(L.initial),address:esc(L.address),phone:esc(L.phone),phoneTel:L.phoneTel,city:esc(city),
 review0:esc(L.reviews[0]),reviewCards:L.reviews.map(r=>'<div class="card"><p>&ldquo;'+esc(r)+'&rdquo;</p><small>GOOGLE REVIEW</small></div>').join(''),
 mapsLink:'https://www.google.com/maps/search/?api=1&query='+q,mapsEmbed:'https://www.openstreetmap.org/export/embed.html?bbox='+[L.lon-.006,L.lat-.0035,L.lon+.006,L.lat+.0035].join('%2C')+'&layer=mapnik&marker='+L.lat+'%2C'+L.lon,
 shopJson:JSON.stringify(L).replace(/</g,'\\u003c')};
V.ratingLine=L.rating?'&#9733; '+esc(L.rating.value)+' on Google ('+esc(L.rating.count)+' reviews) &middot; ':'';
V.serviceTitle=esc(L.serviceTitle||'Auto repair');V.serviceText=esc(L.serviceText||('Describe the problem over the phone and the shop will take it from there. Call '+L.phone+' for a quote.'));
const SV=(L.services&&typeof L.services[0]==='object')?L.services:[{t:L.serviceTitle||'Auto repair',d:L.serviceText||('Describe the problem over the phone and the shop will take it from there. Call '+L.phone+' for a quote.')}];
const ICO='<svg viewBox="0 0 24 24" width="28" height="28" aria-hidden="true"><path fill="currentColor" d="M22 19.600 13.400 11a5.500 5.500 0 0 0-7.300-6.800l3.700 3.700-2.100 2.100L3.900 6.300A5.500 5.500 0 0 0 11 13.400l8.600 8.600z"/></svg>';
V.ddArrow=SV.length>1?' <span class="car">&#9662;</span>':'';
V.svcMenu=SV.length>1?'<div class="menu">'+SV.map(s=>'<a href="#services">'+esc(s.t)+'</a>').join('')+'</div>':'';
V.servicesSection='<section id="services" class="sec"><div class="wrap"><p class="eyebrow dark">SERVICES</p><h2>'+(SV.length>1?'What the shop does.':'What they do.')+'</h2><div class="svcs">'+SV.map(s=>'<div class="svcc"><div class="ico">'+ICO+'</div><div><h3>'+esc(s.t)+'</h3><p>'+esc(s.d)+'</p>'+(s.src?'<small>'+esc(s.src)+'</small>':'')+'</div></div>').join('')+'</div><div class="cta" style="margin-top:28px"><a class="btn" href="tel:'+L.phoneTel+'">Call '+esc(L.phone)+'</a></div></div></section>';
const R5=!!L.reviewStars;const star='<span class="stars" aria-label="5 stars">&#9733;&#9733;&#9733;&#9733;&#9733;</span>';
V.reviewsSection='<section id="reviews" class="sec '+(L.rating?'proud':'alt')+'"><div class="wrap"><p class="eyebrow'+(L.rating?'':' dark')+'">WHAT CUSTOMERS SAY</p><h2>'+(L.rating?'Proud of the work. Customers say so.':'Real words from Google reviews.')+'</h2>'+(L.rating?'<div class="stats"><div class="stat"><b>&#9733; '+esc(L.rating.value)+'</b><span>Google rating</span></div><div class="stat"><b>'+esc(L.rating.count)+'</b><span>Google reviews</span></div></div>':'')+'<div class="rev">'+L.reviews.map(r=>'<div class="card'+(R5?' ach':'')+'">'+(R5?star:'')+'<p>&ldquo;'+esc(r)+'&rdquo;</p><small>'+(R5?'5-STAR GOOGLE REVIEW':'GOOGLE REVIEW')+'</small></div>').join('')+'</div></div></section>';
const MS={
car:'<ellipse cx="60" cy="74" rx="46" ry="4" fill="#0006"/><path d="M14 54c0-9 4-14 12-17l12-17c3-4 6-6 11-6h22c6 0 9 2 12 6l12 17c9 3 13 8 13 17v8H14z" fill="var(--a)"/><path d="M42 22h36l9 15H33z" fill="#dff7ff" opacity=".9"/><circle cx="42" cy="46" r="9" fill="#fff"/><circle cx="78" cy="46" r="9" fill="#fff"/><circle cx="44" cy="47" r="4.500" fill="#080a08"/><circle cx="80" cy="47" r="4.500" fill="#080a08"/><path d="M48 60q12 9 24 0" fill="none" stroke="#080a08" stroke-width="3.500" stroke-linecap="round"/><circle cx="32" cy="70" r="11" fill="#080a08"/><circle cx="32" cy="70" r="5" fill="#aab3aa"/><circle cx="88" cy="70" r="11" fill="#080a08"/><circle cx="88" cy="70" r="5" fill="#aab3aa"/>',
tire:'<ellipse cx="60" cy="74" rx="40" ry="4" fill="#0006"/><circle cx="60" cy="40" r="34" fill="#080a08"/><circle cx="60" cy="40" r="22" fill="var(--a)"/><circle cx="50" cy="36" r="6" fill="#fff"/><circle cx="70" cy="36" r="6" fill="#fff"/><circle cx="51" cy="37" r="3" fill="#080a08"/><circle cx="71" cy="37" r="3" fill="#080a08"/><path d="M50 49q10 8 20 0" fill="none" stroke="#080a08" stroke-width="3" stroke-linecap="round"/>',
paw:'<ellipse cx="60" cy="74" rx="36" ry="4" fill="#0006"/><ellipse cx="60" cy="52" rx="26" ry="21" fill="var(--a)"/><ellipse cx="28" cy="34" rx="10" ry="13" fill="var(--a)"/><ellipse cx="46" cy="20" rx="10" ry="13" fill="var(--a)"/><ellipse cx="74" cy="20" rx="10" ry="13" fill="var(--a)"/><ellipse cx="92" cy="34" rx="10" ry="13" fill="var(--a)"/><circle cx="51" cy="50" r="5" fill="#fff"/><circle cx="69" cy="50" r="5" fill="#fff"/><circle cx="52" cy="51" r="2.500" fill="#080a08"/><circle cx="70" cy="51" r="2.500" fill="#080a08"/><path d="M52 61q8 6 16 0" fill="none" stroke="#080a08" stroke-width="3" stroke-linecap="round"/>',
scissors:'<ellipse cx="60" cy="74" rx="36" ry="4" fill="#0006"/><circle cx="60" cy="42" r="30" fill="var(--a)"/><circle cx="50" cy="38" r="6" fill="#fff"/><circle cx="70" cy="38" r="6" fill="#fff"/><circle cx="51" cy="39" r="3" fill="#080a08"/><circle cx="71" cy="39" r="3" fill="#080a08"/><path d="M48 52q12 9 24 0" fill="none" stroke="#080a08" stroke-width="3" stroke-linecap="round"/><path d="M34 22l-8-12M86 22l8-12" stroke="#080a08" stroke-width="4" stroke-linecap="round"/><circle cx="24" cy="8" r="5" fill="none" stroke="#080a08" stroke-width="3"/><circle cx="96" cy="8" r="5" fill="none" stroke="#080a08" stroke-width="3"/>',
chef:'<ellipse cx="60" cy="76" rx="36" ry="4" fill="#0006"/><circle cx="60" cy="52" r="24" fill="var(--a)"/><path d="M34 34q-12-16 8-20q4-12 18-8q14-4 18 8q20 4 8 20z" fill="#fff"/><rect x="38" y="30" width="44" height="8" fill="#fff"/><circle cx="51" cy="52" r="5" fill="#fff"/><circle cx="69" cy="52" r="5" fill="#fff"/><circle cx="52" cy="53" r="2.500" fill="#080a08"/><circle cx="70" cy="53" r="2.500" fill="#080a08"/><path d="M50 63q10 8 20 0" fill="none" stroke="#080a08" stroke-width="3" stroke-linecap="round"/>',
sparkle:'<ellipse cx="60" cy="74" rx="36" ry="4" fill="#0006"/><circle cx="60" cy="44" r="28" fill="var(--a)"/><path d="M36 38q12-12 24-4q12-8 24 4" fill="none" stroke="#080a08" stroke-width="5" stroke-linecap="round"/><circle cx="50" cy="46" r="5" fill="#fff"/><circle cx="70" cy="46" r="5" fill="#fff"/><circle cx="51" cy="47" r="2.500" fill="#080a08"/><circle cx="71" cy="47" r="2.500" fill="#080a08"/><path d="M50 58q10 8 20 0" fill="none" stroke="#080a08" stroke-width="3" stroke-linecap="round"/><path d="M100 14l3 8 8 3-8 3-3 8-3-8-8-3 8-3z" fill="var(--a)"/>'};
V.mascotSvg='<svg class="mascot" viewBox="0 0 120 80" aria-hidden="true">'+(MS[L.mascotKind||'car'])+'</svg>';
V.headline=L.headline||'Auto repair in<br><em>Fort Wayne,</em> Indiana.';
V.leadText=esc(L.leadText||(L.name+' at '+L.address+'. Tell them what your car is doing and get it looked at.'));
const AS=path.join('assets',L.slug),IM=L.images||{};const has=k=>IM[k]&&fs.existsSync(path.join(AS,IM[k].file));
V.heroAttr=has('hero')?'class="hero has-img" data-hero="'+IM.hero.file+'"':'class="hero"';
V.logoHtml=has('logo')?'<img class="logo-img'+(IM.logo.square?' logo-sq':'')+'" data-img="'+IM.logo.file+'" alt="'+esc(L.short)+' logo">':'<span class="mark">'+esc(L.initial)+'</span>';
const gk=(IM.gallery||[]).filter(g=>fs.existsSync(path.join(AS,g.file)));
V.gallerySection=gk.length?'<section id="gallery" class="sec"><div class="wrap"><p class="eyebrow dark">THE SHOP</p><h2>Photos from the shop.</h2><div class="gal">'+gk.map((g,i)=>'<figure'+(g.tall?' class="tall"':'')+'><img data-img="'+g.file+'" alt="'+esc(g.alt)+'"><figcaption>'+esc(g.caption)+'</figcaption></figure>').join('')+'</div><p class="note dark">Photos from the shop\'s public listings and social pages.</p></div></section>':'';
const out=path.join('out',L.slug);fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
const sub=s=>s.replace(/\{\{(\w+)\}\}/g,(m,k)=>{if(!(k in V))throw new Error('missing '+k);return V[k]});
fs.writeFileSync(path.join(out,'index.html'),sub(fs.readFileSync('template-modern/index.html','utf8')));
const css=fs.readFileSync('template-modern/style.css','utf8').split('#ffd23f').join(TH.accent).split('#14171c').join(TH.ink).split('#262c36').join(TH.ink2).split('#2a3140').join(TH.glow).split('#b07d00').join(TH.accentDark).replace('--a:'+TH.accent,'--a:'+TH.accent);
fs.writeFileSync(path.join(out,'style.css'),css);if(fs.existsSync(AS)){const M={};const {execSync}=require('child_process');for(const f of fs.readdirSync(AS)){const t='/tmp/_s_'+f;const mx=/hero|shop/.test(f)?1000:(/logo/.test(f)?160:640);execSync('python3 -c "from PIL import Image;im=Image.open(\''+path.join(AS,f)+'\').convert(\'RGB\');im.thumbnail(('+mx+','+mx+'));im.save(\''+t+'\',quality=62,optimize=True)"');M[f]='data:image/jpeg;base64,'+fs.readFileSync(t).toString('base64');}
fs.writeFileSync(path.join(out,'img.js'),'(function(){var M='+JSON.stringify(M)+';document.querySelectorAll("[data-img]").forEach(function(e){e.src=M[e.getAttribute("data-img")]});document.querySelectorAll("[data-hero]").forEach(function(e){e.style.setProperty("--hero","url("+M[e.getAttribute("data-hero")]+")")})})();');}
if(!fs.existsSync(path.join(out,'img.js')))fs.writeFileSync(path.join(out,'img.js'),'/* no photos */');
fs.copyFileSync('template-modern/chat.js',path.join(out,'chat.js'));
console.log('built',out);
if(L.revSrc){for(const f of ['index.html','chat.js']){const p=path.join(out,f);let t=fs.readFileSync(p,'utf8');t=t.split('Google reviews').join(L.revSrc+' reviews').split('Google review').join(L.revSrc+' review').split('GOOGLE REVIEW').join(L.revSrc.toUpperCase()+' REVIEW').split('Google rating').join(L.revSrc+' rating');fs.writeFileSync(p,t);}}
if(L.noCall){const p=path.join(out,'index.html');let t=fs.readFileSync(p,'utf8');t=t.replace(/<a[^>]*href="tel:[^"]*"[^>]*>[\s\S]*?<\/a>/g,'');fs.writeFileSync(p,t);}
